name: dot_music
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.6.1
  on_audio_query: ^2.9.0
  go_router: ^16.2.1
  just_audio: ^0.9.35
  sqflite: ^2.4.2
  path_provider: ^2.1.5 
  path: ^1.9.1
  audio_service: ^0.18.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
